// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED BY THE MAKEFILE (see target for instructions.h)
#include "ptx_ir.h"
#ifndef instructions_h_included
#define instructions_h_included
#ifdef __cplusplus
extern "C" {
#endif
void abs_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void add_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void addc_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void and_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void atom_impl( const ptx_instruction *pI, ptx_thread_info *thread );
void bar_sync_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void bra_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void brkpt_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void call_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void cnot_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void cos_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void cvt_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void div_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void ex2_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void exit_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void ld_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void lg2_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void mad24_impl( const ptx_instruction *pI, ptx_thread_info *thread );
void mad_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void max_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void membar_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void min_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void mov_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void mul24_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void mul_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void neg_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void not_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void or_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void rcp_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void red_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void rem_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void ret_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void rsqrt_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void sad_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void selp_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void setp_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void set_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void shl_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void shr_impl( const ptx_instruction *pI, ptx_thread_info *thread );
void sin_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void slct_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void sqrt_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void st_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void sub_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void tex_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void trap_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void vote_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
void xor_impl( const ptx_instruction *pI, ptx_thread_info *thread ) ;
#ifdef __cplusplus
}
#endif
#endif
