
#line 3 "lex.ptx_.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer ptx__create_buffer
#define yy_delete_buffer ptx__delete_buffer
#define yy_flex_debug ptx__flex_debug
#define yy_init_buffer ptx__init_buffer
#define yy_flush_buffer ptx__flush_buffer
#define yy_load_buffer_state ptx__load_buffer_state
#define yy_switch_to_buffer ptx__switch_to_buffer
#define yyin ptx_in
#define yyleng ptx_leng
#define yylex ptx_lex
#define yylineno ptx_lineno
#define yyout ptx_out
#define yyrestart ptx_restart
#define yytext ptx_text
#define yywrap ptx_wrap
#define yyalloc ptx_alloc
#define yyrealloc ptx_realloc
#define yyfree ptx_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE ptx_restart(ptx_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int ptx_leng;

extern FILE *ptx_in, *ptx_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE ptx_lex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-ptx_lineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < ptx_leng; ++yyl )\
                    if ( ptx_text[yyl] == '\n' )\
                        --ptx_lineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up ptx_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up ptx_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via ptx_restart()), so that the user can continue scanning by
	 * just pointing ptx_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when ptx_text is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int ptx_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow ptx_wrap()'s to do buffer switches
 * instead of setting up a fresh ptx_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void ptx_restart (FILE *input_file  );
void ptx__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE ptx__create_buffer (FILE *file,int size  );
void ptx__delete_buffer (YY_BUFFER_STATE b  );
void ptx__flush_buffer (YY_BUFFER_STATE b  );
void ptx_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void ptx_pop_buffer_state (void );

static void ptx_ensure_buffer_stack (void );
static void ptx__load_buffer_state (void );
static void ptx__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER ptx__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE ptx__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE ptx__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE ptx__scan_bytes (yyconst char *bytes,int len  );

void *ptx_alloc (yy_size_t  );
void *ptx_realloc (void *,yy_size_t  );
void ptx_free (void *  );

#define yy_new_buffer ptx__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        ptx_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            ptx__create_buffer(ptx_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        ptx_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            ptx__create_buffer(ptx_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define ptx_wrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *ptx_in = (FILE *) 0, *ptx_out = (FILE *) 0;

typedef int yy_state_type;

extern int ptx_lineno;

int ptx_lineno = 1;

extern char *ptx_text;
#define yytext_ptr ptx_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up ptx_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	ptx_leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 190
#define YY_END_OF_BUFFER 191
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[765] =
    {   0,
        0,    0,  188,  188,    0,    0,    0,    0,  191,  189,
      180,  178,  179,  172,  186,   81,   81,  168,  169,  161,
      162,  189,  176,  189,   83,   83,  170,  171,  166,  173,
      167,  163,  164,  165,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,  174,  175,
      188,  187,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  183,  185,  184,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  189,  178,   81,   81,   81,   81,   81,
       83,  155,  156,  157,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  158,  159,  160,  181,  177,
        0,   83,    0,    0,    0,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   14,   81,   81,
       81,   81,   81,   81,   81,   81,   26,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   40,   81,   81,   81,
       81,   81,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  188,   14,  188,  188,  188,  188,
      188,  188,  188,  188,   26,  188,  188,  188,  188,  188,
      188,  188,  188,  188,   40,  188,  188,  188,  188,  188,

      183,  182,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,   14,  183,  183,  183,  183,  183,
      183,  183,  183,   26,  183,  183,  183,  183,  183,  183,
      183,  183,  183,   40,  183,  183,  183,  183,  183,   81,
       81,   81,   81,   81,   81,  152,  153,  154,    0,    0,
        0,    0,    0,    0,    0,   98,    0,    0,    0,    0,
        0,    0,  115,    0,    0,    0,    0,    0,    0,    0,
      120,  140,  119,  123,  124,    0,  118,  121,  122,  117,
        0,    0,    0,  116,    0,  143,    0,    0,    0,  131,
      129,  132,  130,    0,    0,    0,   87,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,   91,    0,
      103,  104,  105,    0,    0,    0,    0,  177,   82,    0,
        0,   84,    1,    2,    3,   81,   81,    6,   81,   81,
       81,    9,   10,   11,   12,   81,    0,   81,   16,   18,
       19,   81,   20,   21,   23,   24,   25,   27,   48,   28,
       29,   81,   31,   81,   34,   35,   36,   37,   81,   81,
        0,   81,   42,   43,   81,   81,   46,    1,    2,    3,
      188,  188,    6,  188,  188,  188,    9,   10,   11,   12,
      188,  188,   16,   18,   19,  188,   20,   21,   23,   24,
       25,   27,   48,   28,   29,  188,   31,  188,   34,   35,

       36,   37,  188,  188,  188,   42,   43,  188,  188,   46,
        1,    2,    3,  183,  183,    6,  183,  183,  183,    9,
       10,   11,   12,  183,  183,   16,   18,   19,  183,   20,
       21,   23,   24,   25,   27,   48,   28,   29,  183,   31,
      183,   34,   35,   36,   37,  183,  183,  183,   42,   43,
      183,  183,   46,   81,   81,   81,   81,   81,   80,  147,
        0,  139,  142,  138,    0,   99,  100,  101,    0,  145,
        0,  141,  149,    0,  106,    0,    0,   95,   96,   97,
        0,  133,    0,    0,  111,    0,  110,  148,  109,   61,
      108,  151,  150,  113,  107,  112,    0,    0,   63,  127,

      125,  128,  126,   88,   89,   90,  114,    0,    0,    0,
        0,    0,    0,   70,   92,   93,   94,  135,    0,    0,
        0,  144,    0,    0,   50,    4,    0,   81,   81,    7,
        8,   13,    0,   81,   81,   81,   81,   81,   32,   33,
       38,   39,    0,   81,   44,   45,   50,    4,  188,  188,
        7,    8,   13,  188,  188,  188,  188,  188,   32,   33,
       38,   39,  188,   44,   45,   50,    4,  183,  183,    7,
        8,   13,  183,  183,  183,  183,  183,   32,   33,   38,
       39,  183,   44,   45,   81,   81,   81,   81,   77,    0,
        0,   52,    0,    0,  146,    0,   57,  137,   58,    0,

        0,    0,    0,  102,    0,    0,   66,    0,   68,    0,
        0,    0,    0,  134,    0,    0,    0,   81,   49,    0,
       81,   17,   81,   22,   30,    0,   81,  188,   49,  188,
       17,  188,   22,   30,  188,  183,   49,  183,   17,  183,
       22,   30,  183,   75,   76,   81,   81,   51,    0,   54,
       55,    0,    0,   60,    0,   62,    0,    0,    0,    0,
       71,    0,    0,    0,    0,    0,   81,    0,   81,   47,
        0,   81,  188,  188,   47,  188,  183,  183,   47,  183,
       78,   79,  136,    0,   56,   59,    0,    0,   65,   67,
       69,    0,    0,    0,    0,    0,   81,    0,   81,    0,

       81,  188,  188,  188,  183,  183,  183,    0,   74,   64,
       72,   73,    0,    0,    5,    5,    0,   81,    0,   81,
        5,  188,  188,    5,  183,  183,   53,    0,    0,    0,
       81,    0,   81,  188,  188,  183,  183,    0,   85,    0,
       81,    0,   81,  188,  188,  183,  183,    0,   15,   15,
       41,   41,   15,   41,   15,   41,    0,    0,    0,    0,
        0,    0,   86,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    7,    8,    1,    1,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   22,   24,   22,   25,   26,   27,
       28,   29,    1,   30,   31,   31,   31,   32,   31,   33,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,   34,    7,    7,
       35,    1,   36,    1,    7,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,    7,   46,   47,   48,   49,
       50,   51,   52,   53,   54,   55,   56,   57,   58,   59,
       60,   61,   62,    1,   63,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[64] =
    {   0,
        1,    1,    2,    1,    1,    3,    4,    1,    1,    1,
        5,    1,    1,    1,    1,    1,    6,    6,    6,    6,
        6,    6,    6,    6,    1,    1,    1,    1,    1,    1,
        6,    6,    6,    4,    1,    1,    6,    6,    6,    6,
        6,    6,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    1,    1
    } ;

static yyconst flex_int16_t yy_base[805] =
    {   0,
        0,    0,   58,  112,  169,  226,  280,    0, 1055, 1056,
     1056,    0, 1056, 1056, 1056,    0,   26, 1056, 1056, 1056,
     1056,   65,  323,   55,  370,  104, 1056, 1056, 1056, 1056,
     1056, 1056, 1056, 1056,   54,   37,   83, 1009,  994,   27,
       98,   27,  999,   37,  137,   61, 1001, 1000, 1056, 1056,
        0, 1056,  130,   63,  107, 1004,  989,   61,  146,   88,
      994,  134,  194,   89,  996,  995,    0, 1056, 1028,  165,
       94,  195,  998,  983,   94,  206,   95,  988,  158,  247,
      105,  990,  989, 1022,    0,    0,   25,  984,  156,  991,
      287, 1056,  995,  994,  993,  208,  326,  203,  991,  219,

      377,  246,  132,  982,  297,  118,  157,  977,  217,  275,
      416,  163,  393,  386,  984,  978, 1056, 1056, 1056,    0,
      426,  444,    0,    0,  456,  973,  986,  985,  974,  970,
      184,  975,  971,  966,  964,  961,  182,  480,  998,  175,
      968,  966,  957,  966,  969,  956,    0,  959,  242,  957,
      968,  178,   26,  958,  967,  952,  543,  966,  944,  965,
      946,  947,    0,  945,  958,  957,  946,  942,  223,  947,
      943,  938,  936,  933,  253,  309,  970,  202,  940,  938,
      929,  938,  941,  928,    0,  931,  375,  929,  940,  267,
      242,  930,  939,  924,  342,  938,  916,  937,  918,  919,

        0, 1056,  917,  930,  929,  918,  914,  362,  919,  915,
      910,  908,  905,  312,  950,  941,  273,  911,  909,  900,
      909,  912,  899,    0,  902,  380,  900,  911,  354,  306,
      901,  910,  895,  936,  908,  886,  907,  888,  889,  891,
      903,  894,  883,  892,  896, 1056, 1056, 1056,  895,  309,
      315,  883,  910,  913,  910, 1056,  875,  875,  879,  890,
      887,  870,  868,  359,  900,  903,  900,  873,  858,  372,
      862,  867,  860, 1056, 1056,  876,  858,  874, 1056,  856,
      852,  861,  860,  852,  859, 1056,  853,  864,  861,  858,
      857,  856,  855,  876,  879,  876, 1056,  841,  856,  857,

      852,  839,  838,  837,  830,  865,  868,  865, 1056,  840,
     1056, 1056, 1056,  831,  829,  842,  828,    0,  480,    0,
        0,  500,    0,  841,    0,  831,  606,    0,  827,  830,
      821,    0,    0,    0,    0,  820,  817,  816,    0,  853,
        0,  833,    0,    0,  851,    0,    0,    0,    0,    0,
        0,  816,    0,  817,  816,    0,    0,    0,  811,  810,
      807,  806,    0,    0,  811,  820,    0,    0,  821,    0,
      811,  435,    0,  807,  810,  801,    0,    0,    0,    0,
      800,  797,    0,  834,    0,  814,    0,    0,  832,    0,
        0,    0,    0,    0,    0,  797,    0,  798,  797,    0,

        0,    0,  792,  791,  788,    0,    0,  793,  802,    0,
        0,  803,    0,  793,  829,    0,  788,  791,  782,    0,
        0,    0,    0,  781,  778,    0,  815,    0,  795,    0,
        0,  813,    0,    0,    0,    0,    0,    0,  778,    0,
      779,  778,    0,    0,    0,  773,  772,  769,    0,    0,
      774,  783,    0,  784,  777,  781,  783,  779,    0, 1056,
      775, 1056, 1056, 1056,  764, 1056, 1056, 1056,  775, 1056,
      761, 1056, 1056,  761, 1056,  769,  771, 1056, 1056, 1056,
      770, 1056,  763,  770, 1056,  770, 1056, 1056, 1056,  770,
     1056,  757, 1056, 1056, 1056, 1056,  768,  764, 1056, 1056,

     1056, 1056, 1056, 1056, 1056, 1056, 1056,  748,  749,  758,
      744,  757,  755, 1056, 1056, 1056, 1056,  747,  742,  750,
      753, 1056,    0,    0,    0,    0,  739,  738,  736,    0,
        0,    0,  740,  739,  767,  750,  765,  730,    0,    0,
        0,    0,  734,  733,    0,    0,    0,    0,  728,  726,
        0,    0,    0,  730,  758,  741,  756,  721,    0,    0,
        0,    0,  725,    0,    0,    0,    0,  720,  718,    0,
        0,    0,  722,  750,  733,  748,  713,    0,    0,    0,
        0,  717,    0,    0,  720,  725,  719,  718,    0,  709,
      696, 1056,  685,  674, 1056,  663, 1056, 1056, 1056,  673,

      657,  646,  650, 1056,  648,  648, 1056,  644, 1056,  626,
      617,  620,  626, 1056,    0,    0,  603,  602,    0,  614,
      613,    0,  606,    0,    0,  611,  610,  596,    0,  608,
        0,  601,    0,    0,  606,  592,    0,  604,    0,  597,
        0,    0,  602,    0,    0,  608,  607, 1056,  587,  610,
     1056,  595,  596, 1056,  595, 1056,  589,  598,  582,  575,
     1056,  579,  581,    0,    0,  578,  577,  588,  587,    0,
      586,  576,  560,  567,    0,  566,  553,  564,    0,  563,
        0,    0, 1056,  508, 1056, 1056,  558,  548, 1056, 1056,
     1056,  547,  554,    0,    0,  555,  554,  537,  536,  535,

      534,  549,  522,  521,  536,  519,  512,  563, 1056, 1056,
     1056, 1056,    0,    0, 1056,    0,  521,  520,  519,  518,
        0,  517,  516,    0,  515,  505, 1056,    0,    0,  499,
      494,  493,  492,  491,  490,  489,  488,    0, 1056,  493,
      492,  473,  472,  471,  470,  446,  442,    0, 1056,    0,
     1056,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0, 1056, 1056,  669,  675,  681,  684,  690,  696,
      702,  464,  452,  708,  714,  720,  726,  732,  738,  450,
      449,  744,  750,  756,  448,  446,  445,  431,  420,  419,
      418,  412,  390,  363,  352,  319,  294,  271,  230,  184,

      170,  135,  104,   87
    } ;

static yyconst flex_int16_t yy_def[805] =
    {   0,
      764,    1,  765,  765,  766,  766,    1,    7,  764,  764,
      764,  767,  764,  764,  764,  768,  768,  764,  764,  764,
      764,  764,  764,  764,  764,  764,  764,  764,  764,  764,
      764,  764,  764,  764,  768,  768,  768,  768,  768,  768,
      768,  768,  768,  768,  768,  768,  768,  768,  764,  764,
      769,  764,  769,  769,  769,  769,  769,  769,  769,  769,
      769,  769,  769,  769,  769,  769,  770,  764,  764,  770,
      770,  770,  770,  770,  770,  770,  770,  770,  770,  770,
      770,  770,  770,  764,  767,  768,  768,  768,  768,  768,
      764,  764,  764,  764,  764,  764,  764,  764,  764,  764,

      764,  764,  764,  764,  764,  764,  764,  764,  764,  764,
      764,  764,  764,  764,  764,  764,  764,  764,  764,  771,
      764,  764,  772,  773,  764,  768,  768,  768,  768,  768,
      768,  768,  768,  768,  768,  768,  768,  774,  768,  768,
      768,  768,  768,  768,  768,  768,  768,  768,  768,  768,
      768,  768,  768,  768,  768,  768,  775,  768,  768,  768,
      768,  768,  769,  769,  769,  769,  769,  769,  769,  769,
      769,  769,  769,  769,  769,  776,  769,  769,  769,  769,
      769,  769,  769,  769,  769,  769,  769,  769,  769,  769,
      769,  769,  769,  769,  777,  769,  769,  769,  769,  769,

      770,  764,  770,  770,  770,  770,  770,  770,  770,  770,
      770,  770,  770,  770,  778,  770,  770,  770,  770,  770,
      770,  770,  770,  770,  770,  770,  770,  770,  770,  770,
      770,  770,  770,  779,  770,  770,  770,  770,  770,  768,
      768,  768,  768,  768,  768,  764,  764,  764,  764,  764,
      764,  764,  764,  764,  764,  764,  764,  764,  764,  764,
      764,  764,  764,  764,  764,  764,  764,  764,  764,  764,
      764,  764,  764,  764,  764,  764,  764,  764,  764,  764,
      764,  764,  764,  764,  764,  764,  764,  764,  764,  764,
      764,  764,  764,  764,  764,  764,  764,  764,  764,  764,

      764,  764,  764,  764,  764,  764,  764,  764,  764,  764,
      764,  764,  764,  764,  764,  764,  764,  771,  764,  780,
      781,  764,  768,  768,  768,  768,  782,  768,  768,  768,
      768,  768,  768,  768,  768,  768,  764,  768,  768,  768,
      768,  768,  768,  768,  768,  768,  768,  768,  768,  768,
      768,  768,  768,  768,  768,  768,  768,  768,  768,  768,
      764,  768,  768,  768,  768,  768,  768,  769,  769,  769,
      769,  783,  769,  769,  769,  769,  769,  769,  769,  769,
      769,  769,  769,  769,  769,  769,  769,  769,  769,  769,
      769,  769,  769,  769,  769,  769,  769,  769,  769,  769,

      769,  769,  769,  769,  769,  769,  769,  769,  769,  769,
      770,  770,  770,  770,  784,  770,  770,  770,  770,  770,
      770,  770,  770,  770,  770,  770,  770,  770,  770,  770,
      770,  770,  770,  770,  770,  770,  770,  770,  770,  770,
      770,  770,  770,  770,  770,  770,  770,  770,  770,  770,
      770,  770,  770,  768,  768,  768,  768,  768,  768,  764,
      764,  764,  764,  764,  764,  764,  764,  764,  764,  764,
      764,  764,  764,  764,  764,  764,  764,  764,  764,  764,
      764,  764,  764,  764,  764,  764,  764,  764,  764,  764,
      764,  764,  764,  764,  764,  764,  764,  764,  764,  764,

      764,  764,  764,  764,  764,  764,  764,  764,  764,  764,
      764,  764,  764,  764,  764,  764,  764,  764,  764,  764,
      764,  764,  785,  786,  768,  768,  764,  768,  768,  768,
      768,  768,  764,  768,  768,  768,  768,  768,  768,  768,
      768,  768,  764,  768,  768,  768,  769,  769,  769,  769,
      769,  769,  769,  769,  769,  769,  769,  769,  769,  769,
      769,  769,  769,  769,  769,  770,  770,  770,  770,  770,
      770,  770,  770,  770,  770,  770,  770,  770,  770,  770,
      770,  770,  770,  770,  768,  768,  768,  768,  768,  764,
      764,  764,  764,  764,  764,  764,  764,  764,  764,  764,

      764,  764,  764,  764,  764,  764,  764,  764,  764,  764,
      764,  764,  764,  764,  787,  788,  764,  768,  768,  764,
      768,  768,  768,  768,  768,  764,  768,  769,  769,  769,
      769,  769,  769,  769,  769,  770,  770,  770,  770,  770,
      770,  770,  770,  768,  768,  768,  768,  764,  764,  764,
      764,  764,  764,  764,  764,  764,  764,  764,  764,  764,
      764,  764,  764,  789,  790,  764,  768,  764,  768,  768,
      764,  768,  769,  769,  769,  769,  770,  770,  770,  770,
      768,  768,  764,  764,  764,  764,  764,  764,  764,  764,
      764,  764,  764,  791,  792,  764,  768,  764,  768,  764,

      768,  769,  769,  769,  770,  770,  770,  764,  764,  764,
      764,  764,  793,  794,  764,  768,  764,  768,  764,  768,
      769,  769,  769,  770,  770,  770,  764,  795,  796,  764,
      768,  764,  768,  769,  769,  770,  770,  797,  764,  764,
      768,  764,  768,  769,  769,  770,  770,  798,  764,  768,
      764,  768,  769,  769,  770,  770,  799,  800,  801,  802,
      803,  804,  764,    0,  764,  764,  764,  764,  764,  764,
      764,  764,  764,  764,  764,  764,  764,  764,  764,  764,
      764,  764,  764,  764,  764,  764,  764,  764,  764,  764,
      764,  764,  764,  764,  764,  764,  764,  764,  764,  764,

      764,  764,  764,  764
    } ;

static yyconst flex_int16_t yy_nxt[1120] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       10,   20,   21,   22,   23,   24,   25,   26,   26,   26,
       26,   26,   26,   26,   27,   28,   29,   30,   31,   32,
       16,   16,   16,   16,   33,   34,   35,   36,   37,   38,
       39,   16,   16,   16,   16,   16,   40,   41,   42,   43,
       16,   16,   44,   45,   46,   16,   47,   16,   48,   16,
       16,   49,   50,   52,   87,  119,  138,  145,   88,  139,
      120,  240,  356,  130,   89,  148,  146,  149,  357,  241,
       90,   91,   91,   91,   91,   91,   91,   91,   91,  131,
      150,  126,  763,  127,   53,   54,   55,   56,   57,  168,

      176,  159,  128,  177,   58,   59,   60,   61,  129,  762,
       62,   63,   64,  160,   65,  169,   66,   52,  121,  132,
      122,  122,  122,  122,  122,  122,  122,  122,  183,  197,
      207,  133,  134,  215,  140,  222,  216,  184,  141,  135,
      761,  198,  142,  170,  223,  236,  208,  143,   53,   54,
       55,   56,   57,  144,  281,  171,  172,  237,   58,   59,
       60,   61,  282,  173,   62,   63,   64,  164,   65,  165,
       66,   68,  186,  151,  187,  760,  274,  152,  166,   69,
      153,  154,  178,  155,  167,  275,  179,  188,  156,  759,
      180,  157,  158,  283,  243,  181,  225,  284,  226,  304,

      335,  182,  203,  305,  204,   70,   71,   72,   73,   74,
      244,  227,  285,  205,  340,   75,   76,   77,   78,  206,
      328,   79,   80,   81,  354,   82,  336,   83,   68,  329,
      189,  209,  355,  341,  190,  758,   69,  191,  192,  258,
      193,  384,  217,  210,  211,  194,  218,  249,  195,  196,
      219,  212,  259,  287,  250,  220,  251,  260,  252,  373,
      385,  221,   70,   71,   72,   73,   74,  262,  374,  288,
      263,  380,   75,   76,   77,   78,  757,  264,   79,   80,
       81,  349,   82,  228,   83,   10,  271,  229,  400,  350,
      230,  231,  272,  232,  401,   84,  351,  381,  233,  748,

      273,  234,  235,   91,   91,   91,   91,   91,   91,   91,
       91,  163,  427,  398,  337,  289,   16,   16,   16,   16,
       16,  399,  290,  291,  739,  292,   16,   16,   16,   16,
      423,  428,   16,   16,   16,  293,   16,  277,   16,   92,
       93,   94,   95,  253,  163,  254,  278,  361,  255,  256,
      279,  280,  443,  461,  463,  462,  424,  738,  444,   96,
       97,   98,   99,  100,  101,  102,  103,  104,  729,  105,
      106,  107,  108,  109,  464,  110,  111,  112,  113,  114,
      115,  116,  117,  118,  121,  257,  122,  122,  122,  122,
      122,  122,  122,  122,  265,  728,  266,  476,  416,  267,

      441,  123,  124,  125,  311,  312,  313,  417,  442,  123,
      306,  124,  307,  477,  393,  308,  309,  714,  483,  436,
      484,  268,  394,  713,  695,  694,  314,  437,  125,  395,
      315,  269,  270,  294,  438,  295,  665,  163,  296,  297,
      527,  310,  319,  319,  319,  319,  319,  319,  319,  319,
      664,  616,  298,  615,  524,  523,  299,  321,  121,  300,
      122,  122,  122,  122,  122,  122,  122,  122,  301,  320,
      302,  303,  322,  322,  322,  322,  322,  322,  322,  322,
      337,  337,  756,  337,  337,  337,  755,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  319,  319,  319,  319,

      319,  319,  319,  319,  337,  337,  337,  337,  337,  337,
      754,  753,  752,  751,  337,  337,  322,  322,  322,  322,
      322,  322,  322,  322,  708,  708,  708,  708,  708,  708,
      708,  708,  750,  749,  747,  746,  745,  744,  743,  742,
      741,  337,  337,  361,  361,  740,  361,  361,  361,  737,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  736,
      735,  734,  733,  732,  731,  730,  726,  361,  361,  361,
      361,  361,  361,  725,  724,  723,  722,  361,  361,  708,
      708,  708,  708,  708,  708,  708,  708,  721,  720,  719,
      718,  717,  716,  715,  712,  711,  710,  709,  727,  707,

      706,  705,  704,  703,  361,  361,  527,  527,  702,  527,
      527,  527,  701,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  700,  699,  698,  697,  696,  693,  692,  691,
      527,  527,  527,  527,  527,  527,  690,  689,  688,  687,
      527,  527,  686,  685,  684,  683,  682,  681,  680,  679,
      678,  677,  676,  675,  674,  673,  672,  671,  670,  669,
      668,  667,  666,  663,  662,  661,  660,  527,  527,   51,
       51,   51,   51,   51,   51,   67,   67,   67,   67,   67,
       67,   85,  659,   85,   85,   85,   85,   86,  658,   86,
      163,  163,  657,  163,  163,  163,  201,  656,  201,  201,

      655,  201,  318,  654,  318,  318,  318,  318,  338,  653,
      338,  338,  338,  338,  362,  652,  362,  362,  362,  362,
      382,  382,  382,  382,  382,  382,  405,  405,  405,  405,
      405,  405,  425,  651,  425,  425,  425,  425,  448,  650,
      448,  448,  448,  448,  528,  649,  528,  528,  528,  528,
      549,  549,  549,  549,  549,  549,  568,  648,  568,  568,
      568,  568,  647,  646,  645,  644,  643,  642,  641,  640,
      639,  638,  637,  636,  635,  634,  633,  632,  631,  630,
      629,  628,  627,  626,  625,  624,  623,  622,  621,  620,
      619,  618,  617,  614,  613,  612,  611,  610,  609,  608,

      607,  606,  605,  604,  603,  602,  601,  600,  599,  598,
      597,  596,  595,  594,  593,  592,  591,  590,  589,  588,
      587,  586,  585,  584,  583,  582,  581,  580,  579,  578,
      577,  576,  575,  574,  573,  572,  571,  570,  569,  527,
      567,  566,  565,  564,  563,  562,  561,  560,  559,  558,
      557,  556,  555,  554,  553,  552,  551,  550,  548,  547,
      546,  545,  544,  543,  542,  541,  540,  539,  538,  537,
      536,  535,  534,  533,  532,  531,  530,  529,  526,  525,
      522,  521,  520,  519,  518,  517,  516,  515,  514,  513,
      512,  511,  510,  509,  508,  507,  506,  505,  504,  503,

      502,  501,  500,  499,  498,  497,  496,  495,  494,  493,
      492,  491,  490,  489,  488,  487,  486,  485,  482,  481,
      480,  479,  478,  475,  474,  473,  472,  471,  470,  469,
      468,  467,  466,  465,  460,  459,  458,  457,  456,  455,
      454,  453,  452,  451,  450,  449,  361,  447,  446,  445,
      440,  439,  435,  434,  433,  432,  431,  430,  429,  426,
      337,  422,  421,  420,  419,  418,  415,  414,  413,  412,
      411,  410,  409,  408,  407,  406,  404,  403,  402,  397,
      396,  392,  391,  390,  389,  388,  387,  386,  383,  379,
      378,  377,  376,  375,  372,  371,  370,  369,  368,  367,

      366,  365,  364,  363,  360,  359,  358,  353,  352,  348,
      347,  346,  345,  344,  343,  342,  339,  334,  333,  332,
      331,  330,  327,  326,  325,  324,  323,  317,  316,  286,
      276,  261,  248,  247,  246,  245,  242,  120,  239,  238,
      224,  214,  213,  202,  200,  199,  185,  175,  174,  162,
      161,  147,  137,  136,  764,    9,  764,  764,  764,  764,
      764,  764,  764,  764,  764,  764,  764,  764,  764,  764,
      764,  764,  764,  764,  764,  764,  764,  764,  764,  764,
      764,  764,  764,  764,  764,  764,  764,  764,  764,  764,
      764,  764,  764,  764,  764,  764,  764,  764,  764,  764,

      764,  764,  764,  764,  764,  764,  764,  764,  764,  764,
      764,  764,  764,  764,  764,  764,  764,  764,  764
    } ;

static yyconst flex_int16_t yy_chk[1120] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,   17,   24,   40,   42,   17,   40,
       24,   87,  153,   36,   17,   44,   42,   44,  153,   87,
       17,   22,   22,   22,   22,   22,   22,   22,   22,   36,
       44,   35,  804,   35,    3,    3,    3,    3,    3,   54,

       58,   46,   35,   58,    3,    3,    3,    3,   35,  803,
        3,    3,    3,   46,    3,   54,    3,    4,   26,   37,
       26,   26,   26,   26,   26,   26,   26,   26,   60,   64,
       71,   37,   37,   75,   41,   77,   75,   60,   41,   37,
      802,   64,   41,   55,   77,   81,   71,   41,    4,    4,
        4,    4,    4,   41,  106,   55,   55,   81,    4,    4,
        4,    4,  106,   55,    4,    4,    4,   53,    4,   53,
        4,    5,   62,   45,   62,  801,  103,   45,   53,    5,
       45,   45,   59,   45,   53,  103,   59,   62,   45,  800,
       59,   45,   45,  107,   89,   59,   79,  107,   79,  112,

      137,   59,   70,  112,   70,    5,    5,    5,    5,    5,
       89,   79,  107,   70,  140,    5,    5,    5,    5,   70,
      131,    5,    5,    5,  152,    5,  137,    5,    6,  131,
       63,   72,  152,  140,   63,  799,    6,   63,   63,   98,
       63,  178,   76,   72,   72,   63,   76,   96,   63,   63,
       76,   72,   98,  109,   96,   76,   96,   98,   96,  169,
      178,   76,    6,    6,    6,    6,    6,  100,  169,  109,
      100,  175,    6,    6,    6,    6,  798,  100,    6,    6,
        6,  149,    6,   80,    6,    7,  102,   80,  191,  149,
       80,   80,  102,   80,  191,    7,  149,  175,   80,  797,

      102,   80,   80,   91,   91,   91,   91,   91,   91,   91,
       91,  176,  217,  190,  176,  110,    7,    7,    7,    7,
        7,  190,  110,  110,  796,  110,    7,    7,    7,    7,
      214,  217,    7,    7,    7,  110,    7,  105,    7,   23,
       23,   23,   23,   97,  195,   97,  105,  195,   97,   97,
      105,  105,  230,  250,  251,  250,  214,  795,  230,   23,
       23,   23,   23,   23,   23,   23,   23,   23,  794,   23,
       23,   23,   23,   23,  251,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   25,   97,   25,   25,   25,   25,
       25,   25,   25,   25,  101,  793,  101,  264,  208,  101,

      229,   25,   25,   25,  114,  114,  114,  208,  229,   25,
      113,   25,  113,  264,  187,  113,  113,  792,  270,  226,
      270,  101,  187,  791,  790,  789,  114,  226,   25,  187,
      114,  101,  101,  111,  226,  111,  788,  372,  111,  111,
      372,  113,  121,  121,  121,  121,  121,  121,  121,  121,
      787,  786,  111,  785,  781,  780,  111,  773,  122,  111,
      122,  122,  122,  122,  122,  122,  122,  122,  111,  772,
      111,  111,  125,  125,  125,  125,  125,  125,  125,  125,
      138,  138,  747,  138,  138,  138,  746,  138,  138,  138,
      138,  138,  138,  138,  138,  138,  319,  319,  319,  319,

      319,  319,  319,  319,  138,  138,  138,  138,  138,  138,
      745,  744,  743,  742,  138,  138,  322,  322,  322,  322,
      322,  322,  322,  322,  684,  684,  684,  684,  684,  684,
      684,  684,  741,  740,  737,  736,  735,  734,  733,  732,
      731,  138,  138,  157,  157,  730,  157,  157,  157,  726,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  725,
      723,  722,  720,  719,  718,  717,  707,  157,  157,  157,
      157,  157,  157,  706,  705,  704,  703,  157,  157,  708,
      708,  708,  708,  708,  708,  708,  708,  702,  701,  700,
      699,  698,  697,  696,  693,  692,  688,  687,  708,  680,

      678,  677,  676,  674,  157,  157,  327,  327,  673,  327,
      327,  327,  672,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  671,  669,  668,  667,  666,  663,  662,  660,
      327,  327,  327,  327,  327,  327,  659,  658,  657,  655,
      327,  327,  653,  652,  650,  649,  647,  646,  643,  640,
      638,  636,  635,  632,  630,  628,  627,  626,  623,  621,
      620,  618,  617,  613,  612,  611,  610,  327,  327,  765,
      765,  765,  765,  765,  765,  766,  766,  766,  766,  766,
      766,  767,  608,  767,  767,  767,  767,  768,  606,  768,
      769,  769,  605,  769,  769,  769,  770,  603,  770,  770,

      602,  770,  771,  601,  771,  771,  771,  771,  774,  600,
      774,  774,  774,  774,  775,  596,  775,  775,  775,  775,
      776,  776,  776,  776,  776,  776,  777,  777,  777,  777,
      777,  777,  778,  594,  778,  778,  778,  778,  779,  593,
      779,  779,  779,  779,  782,  591,  782,  782,  782,  782,
      783,  783,  783,  783,  783,  783,  784,  590,  784,  784,
      784,  784,  588,  587,  586,  585,  582,  577,  576,  575,
      574,  573,  569,  568,  563,  558,  557,  556,  555,  554,
      550,  549,  544,  543,  538,  537,  536,  535,  534,  533,
      529,  528,  527,  521,  520,  519,  518,  513,  512,  511,

      510,  509,  508,  498,  497,  492,  490,  486,  484,  483,
      481,  477,  476,  474,  471,  469,  465,  461,  458,  457,
      456,  455,  454,  452,  451,  448,  447,  446,  442,  441,
      439,  432,  429,  427,  425,  424,  419,  418,  417,  415,
      414,  412,  409,  408,  405,  404,  403,  399,  398,  396,
      389,  386,  384,  382,  381,  376,  375,  374,  371,  369,
      366,  365,  362,  361,  360,  359,  355,  354,  352,  345,
      342,  340,  338,  337,  336,  331,  330,  329,  326,  324,
      317,  316,  315,  314,  310,  308,  307,  306,  305,  304,
      303,  302,  301,  300,  299,  298,  296,  295,  294,  293,

      292,  291,  290,  289,  288,  287,  285,  284,  283,  282,
      281,  280,  278,  277,  276,  273,  272,  271,  269,  268,
      267,  266,  265,  263,  262,  261,  260,  259,  258,  257,
      255,  254,  253,  252,  249,  245,  244,  243,  242,  241,
      240,  239,  238,  237,  236,  235,  234,  233,  232,  231,
      228,  227,  225,  223,  222,  221,  220,  219,  218,  216,
      215,  213,  212,  211,  210,  209,  207,  206,  205,  204,
      203,  200,  199,  198,  197,  196,  194,  193,  192,  189,
      188,  186,  184,  183,  182,  181,  180,  179,  177,  174,
      173,  172,  171,  170,  168,  167,  166,  165,  164,  162,

      161,  160,  159,  158,  156,  155,  154,  151,  150,  148,
      146,  145,  144,  143,  142,  141,  139,  136,  135,  134,
      133,  132,  130,  129,  128,  127,  126,  116,  115,  108,
      104,   99,   95,   94,   93,   90,   88,   84,   83,   82,
       78,   74,   73,   69,   66,   65,   61,   57,   56,   48,
       47,   43,   39,   38,    9,  764,  764,  764,  764,  764,
      764,  764,  764,  764,  764,  764,  764,  764,  764,  764,
      764,  764,  764,  764,  764,  764,  764,  764,  764,  764,
      764,  764,  764,  764,  764,  764,  764,  764,  764,  764,
      764,  764,  764,  764,  764,  764,  764,  764,  764,  764,

      764,  764,  764,  764,  764,  764,  764,  764,  764,  764,
      764,  764,  764,  764,  764,  764,  764,  764,  764
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[191] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 
    0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int ptx__flex_debug;
int ptx__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *ptx_text;
#line 1 "ptx.l"
/* 
 * Copyright (c) 2009 by Tor M. Aamodt and the University of British Columbia
 * Vancouver, BC  V6T 1Z4
 * All Rights Reserved.
 *
 * THIS IS A LEGAL DOCUMENT BY DOWNLOADING GPGPU-SIM, YOU ARE AGREEING TO THESE
 * TERMS AND CONDITIONS.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNERS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * 
 * NOTE: The files libcuda/cuda_runtime_api.c and src/cuda-sim/cuda-math.h
 * are derived from the CUDA Toolset available from http://www.nvidia.com/cuda
 * (property of NVIDIA).  The files benchmarks/BlackScholes/ and 
 * benchmarks/template/ are derived from the CUDA SDK available from 
 * http://www.nvidia.com/cuda (also property of NVIDIA).  The files from 
 * src/intersim/ are derived from Booksim (a simulator provided with the 
 * textbook "Principles and Practices of Interconnection Networks" available 
 * from http://cva.stanford.edu/books/ppin/). As such, those files are bound by 
 * the corresponding legal terms and conditions set forth separately (original 
 * copyright notices are left in files from these sources and where we have 
 * modified a file our copyright notice appears before the original copyright 
 * notice).  
 * 
 * Using this version of GPGPU-Sim requires a complete installation of CUDA 
 * which is distributed seperately by NVIDIA under separate terms and 
 * conditions.  To use this version of GPGPU-Sim with OpenCL requires a
 * recent version of NVIDIA's drivers which support OpenCL.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 * 
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 * 
 * 3. Neither the name of the University of British Columbia nor the names of
 * its contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 * 
 * 4. This version of GPGPU-SIM is distributed freely for non-commercial use only.  
 *  
 * 5. No nonprofit user may place any restrictions on the use of this software,
 * including as modified by the user, by any other authorized user.
 * 
 * 6. GPGPU-SIM was developed primarily by Tor M. Aamodt, Wilson W. L. Fung, 
 * Ali Bakhoda, George L. Yuan, at the University of British Columbia, 
 * Vancouver, BC V6T 1Z4
 */
#line 67 "ptx.l"
#include "opcodes.h"
#include "ptx.tab.h"
#include <string.h>

char linebuf[1024];
unsigned col = 0;
#define TC col+=strlen(ptx_text); 
int ptx_error( const char *s );



#line 1089 "lex.ptx_.c"

#define INITIAL 0
#define IN_STRING 1
#define IN_COMMENT 2
#define NOT_OPCODE 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int ptx_lex_destroy (void );

int ptx_get_debug (void );

void ptx_set_debug (int debug_flag  );

YY_EXTRA_TYPE ptx_get_extra (void );

void ptx_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *ptx_get_in (void );

void ptx_set_in  (FILE * in_str  );

FILE *ptx_get_out (void );

void ptx_set_out  (FILE * out_str  );

int ptx_get_leng (void );

char *ptx_get_text (void );

int ptx_get_lineno (void );

void ptx_set_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int ptx_wrap (void );
#else
extern int ptx_wrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( ptx_text, ptx_leng, 1, ptx_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( ptx_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( ptx_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, ptx_in))==0 && ferror(ptx_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(ptx_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int ptx_lex (void);

#define YY_DECL int ptx_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after ptx_text and ptx_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 80 "ptx.l"


#line 1282 "lex.ptx_.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! ptx_in )
			ptx_in = stdin;

		if ( ! ptx_out )
			ptx_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			ptx_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				ptx__create_buffer(ptx_in,YY_BUF_SIZE );
		}

		ptx__load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of ptx_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 765 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1056 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < ptx_leng; ++yyl )
				if ( ptx_text[yyl] == '\n' )
					   
    ptx_lineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 82 "ptx.l"
TC; ptx_lval.int_value = ABS_OP; return OPCODE;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 83 "ptx.l"
TC; ptx_lval.int_value = ADD_OP; return OPCODE;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 84 "ptx.l"
TC; ptx_lval.int_value = AND_OP; return OPCODE;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 85 "ptx.l"
TC; ptx_lval.int_value = ATOM_OP; return OPCODE;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 86 "ptx.l"
TC; ptx_lval.int_value = BAR_OP; return OPCODE;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 87 "ptx.l"
TC; ptx_lval.int_value = BRA_OP; return OPCODE;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 88 "ptx.l"
TC; ptx_lval.int_value = CALL_OP; return OPCODE;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 89 "ptx.l"
TC; ptx_lval.int_value = CNOT_OP; return OPCODE;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 90 "ptx.l"
TC; ptx_lval.int_value = COS_OP; return OPCODE;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 91 "ptx.l"
TC; ptx_lval.int_value = CVT_OP; return OPCODE;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 92 "ptx.l"
TC; ptx_lval.int_value = DIV_OP; return OPCODE;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 93 "ptx.l"
TC; ptx_lval.int_value = EX2_OP; return OPCODE;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 94 "ptx.l"
TC; ptx_lval.int_value = EXIT_OP; return OPCODE;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 95 "ptx.l"
TC; ptx_lval.int_value = LD_OP; return OPCODE;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 96 "ptx.l"
TC; ptx_lval.int_value = LD_OP; return OPCODE;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 97 "ptx.l"
TC; ptx_lval.int_value = LG2_OP; return OPCODE;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 98 "ptx.l"
TC; ptx_lval.int_value = MAD24_OP; return OPCODE;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 99 "ptx.l"
TC; ptx_lval.int_value = MAD_OP; return OPCODE;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 100 "ptx.l"
TC; ptx_lval.int_value = MAX_OP; return OPCODE;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 101 "ptx.l"
TC; ptx_lval.int_value = MIN_OP; return OPCODE;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 102 "ptx.l"
TC; ptx_lval.int_value = MOV_OP; return OPCODE;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 103 "ptx.l"
TC; ptx_lval.int_value = MUL24_OP; return OPCODE;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 104 "ptx.l"
TC; ptx_lval.int_value = MUL_OP; return OPCODE;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 105 "ptx.l"
TC; ptx_lval.int_value = NEG_OP; return OPCODE;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 106 "ptx.l"
TC; ptx_lval.int_value = NOT_OP; return OPCODE;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 107 "ptx.l"
TC; ptx_lval.int_value = OR_OP; return OPCODE;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 108 "ptx.l"
TC; ptx_lval.int_value = RCP_OP; return OPCODE;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 109 "ptx.l"
TC; ptx_lval.int_value = REM_OP; return OPCODE;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 110 "ptx.l"
TC; ptx_lval.int_value = RET_OP; return OPCODE;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 111 "ptx.l"
TC; ptx_lval.int_value = RSQRT_OP; return OPCODE;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 112 "ptx.l"
TC; ptx_lval.int_value = SAD_OP; return OPCODE;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 113 "ptx.l"
TC; ptx_lval.int_value = SELP_OP; return OPCODE;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 114 "ptx.l"
TC; ptx_lval.int_value = SETP_OP; return OPCODE;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 115 "ptx.l"
TC; ptx_lval.int_value = SET_OP; return OPCODE;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 116 "ptx.l"
TC; ptx_lval.int_value = SHL_OP; return OPCODE;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 117 "ptx.l"
TC; ptx_lval.int_value = SHR_OP; return OPCODE;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 118 "ptx.l"
TC; ptx_lval.int_value = SIN_OP; return OPCODE;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 119 "ptx.l"
TC; ptx_lval.int_value = SLCT_OP; return OPCODE;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 120 "ptx.l"
TC; ptx_lval.int_value = SQRT_OP; return OPCODE;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 121 "ptx.l"
TC; ptx_lval.int_value = ST_OP; return OPCODE;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 122 "ptx.l"
TC; ptx_lval.int_value = ST_OP; return OPCODE;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 123 "ptx.l"
TC; ptx_lval.int_value = SUB_OP; return OPCODE;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 124 "ptx.l"
TC; BEGIN(NOT_OPCODE); ptx_lval.int_value = TEX_OP; return OPCODE;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 125 "ptx.l"
TC; ptx_lval.int_value = TRAP_OP; return OPCODE;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 126 "ptx.l"
TC; ptx_lval.int_value = VOTE_OP; return OPCODE;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 127 "ptx.l"
TC; ptx_lval.int_value = XOR_OP; return OPCODE;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 128 "ptx.l"
TC; ptx_lval.int_value = MEMBAR_OP; return OPCODE;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 129 "ptx.l"
TC; ptx_lval.int_value = RED_OP; return OPCODE;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 130 "ptx.l"
TC; ptx_lval.int_value = BRKPT_OP; return OPCODE;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 131 "ptx.l"
TC; ptx_lval.int_value = ADDC_OP; return OPCODE;
	YY_BREAK

case 51:
YY_RULE_SETUP
#line 135 "ptx.l"
TC; return ALIGN_DIRECTIVE;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 136 "ptx.l"
TC; return BYTE_DIRECTIVE;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 137 "ptx.l"
TC; return CONST_DIRECTIVE;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 138 "ptx.l"
TC; return CONST_DIRECTIVE;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 139 "ptx.l"
TC; return ENTRY_DIRECTIVE;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 140 "ptx.l"
TC; return EXTERN_DIRECTIVE;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 141 "ptx.l"
TC; return FILE_DIRECTIVE;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 142 "ptx.l"
TC; return FUNC_DIRECTIVE;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 143 "ptx.l"
TC; return GLOBAL_DIRECTIVE;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 144 "ptx.l"
TC; return LOCAL_DIRECTIVE;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 145 "ptx.l"
TC; return LOC_DIRECTIVE;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 146 "ptx.l"
TC; return PARAM_DIRECTIVE;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 147 "ptx.l"
TC; return REG_DIRECTIVE;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 148 "ptx.l"
TC; return SECTION_DIRECTIVE;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 149 "ptx.l"
TC; return SHARED_DIRECTIVE;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 150 "ptx.l"
TC; return SREG_DIRECTIVE;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 151 "ptx.l"
TC; return STRUCT_DIRECTIVE;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 152 "ptx.l"
TC; return SURF_DIRECTIVE;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 153 "ptx.l"
TC; return TARGET_DIRECTIVE;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 154 "ptx.l"
TC; BEGIN(NOT_OPCODE); return TEX_DIRECTIVE;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 155 "ptx.l"
TC; return UNION_DIRECTIVE;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 156 "ptx.l"
TC; return VERSION_DIRECTIVE;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 157 "ptx.l"
TC; return VISIBLE_DIRECTIVE;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 159 "ptx.l"
TC; return MAXNTID_DIRECTIVE;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 161 "ptx.l"
TC; ptx_lval.int_value = CLOCK_ID; return SPECIAL_REGISTER;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 162 "ptx.l"
TC; ptx_lval.int_value = CTA_ID; return SPECIAL_REGISTER;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 163 "ptx.l"
TC; ptx_lval.int_value = NTID_ID; return SPECIAL_REGISTER;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 164 "ptx.l"
TC; ptx_lval.int_value = GRIDID_ID; return SPECIAL_REGISTER;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 165 "ptx.l"
TC; ptx_lval.int_value = NCTAID_ID; return SPECIAL_REGISTER;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 166 "ptx.l"
TC; ptx_lval.int_value = TID_ID; return SPECIAL_REGISTER;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 168 "ptx.l"
TC; ptx_lval.string_value = strdup(ptx_text); /*printf("\n<<identifier=\"%s\">>\n", ptx_text); fflush(stdout);*/ return IDENTIFIER;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 170 "ptx.l"
TC; sscanf(ptx_text,"%lf", &ptx_lval.double_value); return DOUBLE_OPERAND;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 171 "ptx.l"
TC; ptx_lval.int_value =  atoi(ptx_text); return INT_OPERAND;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 172 "ptx.l"
TC;  sscanf(ptx_text,"%x", &ptx_lval.int_value); return INT_OPERAND;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 173 "ptx.l"
TC; sscanf(ptx_text+2,"%x", (unsigned*)(void*)&ptx_lval.float_value); return FLOAT_OPERAND;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 174 "ptx.l"
TC; sscanf(ptx_text+2,"%Lx", (unsigned long long*)(void*)&ptx_lval.double_value); return DOUBLE_OPERAND;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 176 "ptx.l"
TC;  return S8_TYPE;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 177 "ptx.l"
TC;  return S16_TYPE;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 178 "ptx.l"
TC;  return S32_TYPE;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 179 "ptx.l"
TC;  return S64_TYPE;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 180 "ptx.l"
TC;  return U8_TYPE;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 181 "ptx.l"
TC;  return U16_TYPE;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 182 "ptx.l"
TC;  return U32_TYPE;
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 183 "ptx.l"
TC;  return U64_TYPE;
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 184 "ptx.l"
TC;  return F16_TYPE;
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 185 "ptx.l"
TC;  return F32_TYPE;
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 186 "ptx.l"
TC;  return F64_TYPE;
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 187 "ptx.l"
TC;  return B8_TYPE;
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 188 "ptx.l"
TC;  return B16_TYPE;
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 189 "ptx.l"
TC;  return B32_TYPE;
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 190 "ptx.l"
TC;  return B64_TYPE;
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 191 "ptx.l"
TC;  return PRED_TYPE;
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 193 "ptx.l"
TC; return V2_TYPE;
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 194 "ptx.l"
TC; return V3_TYPE;
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 195 "ptx.l"
TC; return V4_TYPE;
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 197 "ptx.l"
TC; return EQU_OPTION;
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 198 "ptx.l"
TC; return NEU_OPTION;
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 199 "ptx.l"
TC; return LTU_OPTION;
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 200 "ptx.l"
TC; return LEU_OPTION;
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 201 "ptx.l"
TC; return GTU_OPTION;
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 202 "ptx.l"
TC; return GEU_OPTION;
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 203 "ptx.l"
TC; return NUM_OPTION;
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 204 "ptx.l"
TC; return NAN_OPTION;
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 206 "ptx.l"
TC; return SAT_OPTION;
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 208 "ptx.l"
TC; return EQ_OPTION;
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 209 "ptx.l"
TC; return NE_OPTION;
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 210 "ptx.l"
TC; return LT_OPTION;
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 211 "ptx.l"
TC; return LE_OPTION;
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 212 "ptx.l"
TC; return GT_OPTION;
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 213 "ptx.l"
TC; return GE_OPTION;
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 215 "ptx.l"
TC; return LO_OPTION;
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 216 "ptx.l"
TC; return LS_OPTION;
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 217 "ptx.l"
TC; return HI_OPTION;
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 218 "ptx.l"
TC; return HS_OPTION;
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 221 "ptx.l"
TC; return RNI_OPTION;
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 222 "ptx.l"
TC; return RZI_OPTION;
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 223 "ptx.l"
TC; return RMI_OPTION;
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 224 "ptx.l"
TC; return RPI_OPTION;
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 226 "ptx.l"
TC; return RN_OPTION;
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 227 "ptx.l"
TC; return RZ_OPTION;
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 228 "ptx.l"
TC; return RM_OPTION;
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 229 "ptx.l"
TC; return RP_OPTION;
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 231 "ptx.l"
TC; return FTZ_OPTION;
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 233 "ptx.l"
TC; return WIDE_OPTION;
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 234 "ptx.l"
TC; return UNI_OPTION;
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 236 "ptx.l"
TC; return APPROX_OPTION;
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 237 "ptx.l"
TC; return FULL_OPTION;
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 239 "ptx.l"
TC; return ANY_OPTION;
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 240 "ptx.l"
TC; return ALL_OPTION;
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 241 "ptx.l"
TC; return GLOBAL_OPTION;
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 242 "ptx.l"
TC; return CTA_OPTION;
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 244 "ptx.l"
TC; return ATOMIC_AND;
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 245 "ptx.l"
TC; return ATOMIC_OR;
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 246 "ptx.l"
TC; return ATOMIC_XOR;
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 247 "ptx.l"
TC; return ATOMIC_CAS;
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 248 "ptx.l"
TC; return ATOMIC_EXCH;
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 249 "ptx.l"
TC; return ATOMIC_ADD;
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 250 "ptx.l"
TC; return ATOMIC_INC;
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 251 "ptx.l"
TC; return ATOMIC_DEC;
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 252 "ptx.l"
TC; return ATOMIC_MIN;
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 253 "ptx.l"
TC; return ATOMIC_MAX;
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 255 "ptx.l"
TC; return GEOM_MODIFIER_1D;
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 256 "ptx.l"
TC; return GEOM_MODIFIER_2D;
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 257 "ptx.l"
TC; return GEOM_MODIFIER_3D;
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 259 "ptx.l"
TC; ptx_lval.int_value = 0; return DIMENSION_MODIFIER;
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 260 "ptx.l"
TC; ptx_lval.int_value = 1; return DIMENSION_MODIFIER;
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 261 "ptx.l"
TC; ptx_lval.int_value = 2; return DIMENSION_MODIFIER;
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 262 "ptx.l"
TC; ptx_lval.int_value = 0; return DIMENSION_MODIFIER;
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 263 "ptx.l"
TC; ptx_lval.int_value = 1; return DIMENSION_MODIFIER;
	YY_BREAK
case 160:
YY_RULE_SETUP
#line 264 "ptx.l"
TC; ptx_lval.int_value = 2; return DIMENSION_MODIFIER;
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 266 "ptx.l"
TC; return PLUS;
	YY_BREAK
case 162:
YY_RULE_SETUP
#line 267 "ptx.l"
TC; return COMMA;
	YY_BREAK
case 163:
YY_RULE_SETUP
#line 268 "ptx.l"
TC; return PRED;
	YY_BREAK
case 164:
YY_RULE_SETUP
#line 269 "ptx.l"
TC; return LEFT_SQUARE_BRACKET;
	YY_BREAK
case 165:
YY_RULE_SETUP
#line 270 "ptx.l"
TC; return RIGHT_SQUARE_BRACKET;
	YY_BREAK
case 166:
YY_RULE_SETUP
#line 271 "ptx.l"
TC; return LEFT_ANGLE_BRACKET;
	YY_BREAK
case 167:
YY_RULE_SETUP
#line 272 "ptx.l"
TC; return RIGHT_ANGLE_BRACKET;
	YY_BREAK
case 168:
YY_RULE_SETUP
#line 273 "ptx.l"
TC; return LEFT_PAREN;
	YY_BREAK
case 169:
YY_RULE_SETUP
#line 274 "ptx.l"
TC; return RIGHT_PAREN;
	YY_BREAK
case 170:
YY_RULE_SETUP
#line 275 "ptx.l"
TC; return COLON;
	YY_BREAK
case 171:
YY_RULE_SETUP
#line 276 "ptx.l"
TC; BEGIN(INITIAL); return SEMI_COLON;
	YY_BREAK
case 172:
YY_RULE_SETUP
#line 277 "ptx.l"
TC; return EXCLAMATION;
	YY_BREAK
case 173:
YY_RULE_SETUP
#line 278 "ptx.l"
TC; return EQUALS;
	YY_BREAK
case 174:
YY_RULE_SETUP
#line 279 "ptx.l"
TC; return LEFT_BRACE;
	YY_BREAK
case 175:
YY_RULE_SETUP
#line 280 "ptx.l"
TC; return RIGHT_BRACE;
	YY_BREAK
case 176:
YY_RULE_SETUP
#line 281 "ptx.l"
TC; return PERIOD;
	YY_BREAK
case 177:
YY_RULE_SETUP
#line 283 "ptx.l"
TC;	// eat single
	YY_BREAK
case 178:
/* rule 178 can match eol */
YY_RULE_SETUP
#line 285 "ptx.l"
col=0; strncpy(linebuf, ptx_text + 1, 1024); yyless( 1 );
	YY_BREAK
case 179:
YY_RULE_SETUP
#line 287 "ptx.l"
TC;
	YY_BREAK
case 180:
YY_RULE_SETUP
#line 288 "ptx.l"
TC;
	YY_BREAK


case 181:
YY_RULE_SETUP
#line 294 "ptx.l"
BEGIN(IN_COMMENT);
	YY_BREAK


case 182:
YY_RULE_SETUP
#line 297 "ptx.l"
BEGIN(INITIAL);
	YY_BREAK
case 183:
YY_RULE_SETUP
#line 298 "ptx.l"
// eat comment in chunks
	YY_BREAK
case 184:
YY_RULE_SETUP
#line 299 "ptx.l"
// eat the lone star
	YY_BREAK
case 185:
/* rule 185 can match eol */
YY_RULE_SETUP
#line 300 "ptx.l"
TC; 
	YY_BREAK


case 186:
YY_RULE_SETUP
#line 304 "ptx.l"
BEGIN(IN_STRING);
	YY_BREAK


case 187:
YY_RULE_SETUP
#line 307 "ptx.l"
TC; BEGIN(INITIAL); return STRING;
	YY_BREAK
case 188:
/* rule 188 can match eol */
YY_RULE_SETUP
#line 308 "ptx.l"
TC; ptx_lval.string_value = strdup(ptx_text); 
	YY_BREAK

case 189:
YY_RULE_SETUP
#line 311 "ptx.l"
TC; ptx_error((const char*)NULL);
	YY_BREAK
case 190:
YY_RULE_SETUP
#line 313 "ptx.l"
ECHO;
	YY_BREAK
#line 2338 "lex.ptx_.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(IN_STRING):
case YY_STATE_EOF(IN_COMMENT):
case YY_STATE_EOF(NOT_OPCODE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed ptx_in at a new source and called
			 * ptx_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = ptx_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( ptx_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * ptx_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of ptx_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					ptx_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			ptx_restart(ptx_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) ptx_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 765 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 765 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 764);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up ptx_text */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --ptx_lineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					ptx_restart(ptx_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( ptx_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve ptx_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    ptx_lineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void ptx_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        ptx_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            ptx__create_buffer(ptx_in,YY_BUF_SIZE );
	}

	ptx__init_buffer(YY_CURRENT_BUFFER,input_file );
	ptx__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void ptx__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		ptx_pop_buffer_state();
	 *		ptx_push_buffer_state(new_buffer);
     */
	ptx_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	ptx__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (ptx_wrap()) processing, but the only time this flag
	 * is looked at is after ptx_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void ptx__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	ptx_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE ptx__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) ptx_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in ptx__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) ptx_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in ptx__create_buffer()" );

	b->yy_is_our_buffer = 1;

	ptx__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with ptx__create_buffer()
 * 
 */
    void ptx__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		ptx_free((void *) b->yy_ch_buf  );

	ptx_free((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a ptx_restart() or at EOF.
 */
    static void ptx__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	ptx__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then ptx__init_buffer was _probably_
     * called from ptx_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void ptx__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		ptx__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void ptx_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	ptx_ensure_buffer_stack();

	/* This block is copied from ptx__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from ptx__switch_to_buffer. */
	ptx__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void ptx_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	ptx__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		ptx__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void ptx_ensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)ptx_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in ptx_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)ptx_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in ptx_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE ptx__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) ptx_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in ptx__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	ptx__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to ptx_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       ptx__scan_bytes() instead.
 */
YY_BUFFER_STATE ptx__scan_string (yyconst char * yystr )
{
    
	return ptx__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to ptx_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE ptx__scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) ptx_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in ptx__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = ptx__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in ptx__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up ptx_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		ptx_text[ptx_leng] = (yy_hold_char); \
		(yy_c_buf_p) = ptx_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		ptx_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int ptx_get_lineno  (void)
{
        
    return ptx_lineno;
}

/** Get the input stream.
 * 
 */
FILE *ptx_get_in  (void)
{
        return ptx_in;
}

/** Get the output stream.
 * 
 */
FILE *ptx_get_out  (void)
{
        return ptx_out;
}

/** Get the length of the current token.
 * 
 */
int ptx_get_leng  (void)
{
        return ptx_leng;
}

/** Get the current token.
 * 
 */

char *ptx_get_text  (void)
{
        return ptx_text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void ptx_set_lineno (int  line_number )
{
    
    ptx_lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see ptx__switch_to_buffer
 */
void ptx_set_in (FILE *  in_str )
{
        ptx_in = in_str ;
}

void ptx_set_out (FILE *  out_str )
{
        ptx_out = out_str ;
}

int ptx_get_debug  (void)
{
        return ptx__flex_debug;
}

void ptx_set_debug (int  bdebug )
{
        ptx__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from ptx_lex_destroy(), so don't allocate here.
     */

    /* We do not touch ptx_lineno unless the option is enabled. */
    ptx_lineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    ptx_in = stdin;
    ptx_out = stdout;
#else
    ptx_in = (FILE *) 0;
    ptx_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * ptx_lex_init()
     */
    return 0;
}

/* ptx_lex_destroy is for both reentrant and non-reentrant scanners. */
int ptx_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		ptx__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		ptx_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	ptx_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * ptx_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *ptx_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *ptx_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void ptx_free (void * ptr )
{
	free( (char *) ptr );	/* see ptx_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 313 "ptx.l"



extern int g_error_detected;
extern const char *g_filename;

int ptx_error( const char *s )
{
	int i;
	g_error_detected = 1;
	fflush(stdout);
	if( s != NULL )
		printf("%s:%u: Syntax error:\n\n", g_filename, ptx_lineno );
	printf("   %s\n", linebuf );
	printf("   ");
	for( i=0; i < col-1; i++ ) {
		if( linebuf[i] == '\t' ) printf("\t");
		else printf(" ");
	}
			
	printf("^\n\n");
	fflush(stdout);
	//exit(1);
	return 0;
}

